name: poisonous_mushroom_classifier
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter_contrib_nbextensions=0.7.0
  - notebook=6.5.7
  - requests=2.32.5
  - vegafusion-python-embed=1.6.9 
  - python=3.14.0
  - scikit-learn=1.7.2
  - vl-convert-python=1.8.0
  - pandas=2.3.3
  - ipykernel=6.29.5 
  - vegafusion=2.0.3 
  - altair=6.0.0
  - vegafusion-jupyter=1.6.9 
